import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingWhatsAppButton from '@/components/global/FloatingWhatsAppButton';
import { strapiApi } from "@/services/api";
import { Header, Footer } from "@/components/global";
import GlobalProvider from "@/context/GlobalProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clave | Purificadores de Agua",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-expect-error - Strapi API response type is not properly typed
  const { data: global } = await strapiApi.get('/api/global');

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header {...global.header} />
        <GlobalProvider global={global}>
          {children}
          {global.isVisibleContactButton && <FloatingWhatsAppButton />}
          <Footer {...global.footer} />
        </GlobalProvider>
      </body>
    </html>
  );
}
